"""Admin Panel and Subscription domain package for Grok2API Sub."""

from .background import PanelBackground, PanelBackgroundError, PanelBackgroundProvider
from .card import PANEL_CARD_TEMPLATE, build_panel_card_data, panel_render_spec
from .client import AdminClient
from .models import (
    DEFAULT_PANEL_PERIOD,
    PANEL_PERIODS,
    PANEL_SECTION_LABELS,
    PANEL_SECTION_ORDER,
    AccountBlock,
    AuditBehavior,
    AuditBlock,
    ImageBlock,
    ModelAggregate,
    ModelSection,
    PanelReport,
    PanelSectionError,
    RequestTrend,
    RequestTrendPoint,
    VideoBlock,
    aggregate_audit_behavior,
    aggregate_models,
    aggregate_request_trend,
    fmt_bytes,
    parse_account_block,
    parse_audit_block,
    parse_image_block,
    parse_video_block,
)
from .renderer import format_panel_text
from .scheduler import (
    PanelSubscriptionError,
    PanelSubscriptionStore,
    interval_due,
    merge_panel_targets,
    validate_umo,
)

__all__ = [
    "AccountBlock",
    "AdminClient",
    "AuditBehavior",
    "AuditBlock",
    "DEFAULT_PANEL_PERIOD",
    "ImageBlock",
    "ModelAggregate",
    "ModelSection",
    "PANEL_CARD_TEMPLATE",
    "PANEL_PERIODS",
    "PANEL_SECTION_LABELS",
    "PANEL_SECTION_ORDER",
    "PanelBackground",
    "PanelBackgroundError",
    "PanelBackgroundProvider",
    "PanelReport",
    "PanelSectionError",
    "PanelSubscriptionError",
    "PanelSubscriptionStore",
    "RequestTrend",
    "RequestTrendPoint",
    "VideoBlock",
    "aggregate_audit_behavior",
    "aggregate_models",
    "aggregate_request_trend",
    "build_panel_card_data",
    "fmt_bytes",
    "format_panel_text",
    "interval_due",
    "merge_panel_targets",
    "panel_render_spec",
    "parse_account_block",
    "parse_audit_block",
    "parse_image_block",
    "parse_video_block",
    "validate_umo",
]
